name: macOS

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive
    - name: Install dependencies
      run: brew install re2c p7zip cmake sdl2

    - name: Build OSP-Magnum
      run: mkdir build && cd build && cmake ..