name: MacOS

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive
    - name: Install dependencies
      run: brew install re2c p7zip cmake sdl2

    - name: Build OSP-Magnum
      run: |
        scan-build --exclude 3rdparty/newton-dynamics -o scanlogs cmake -B build -DCMAKE_BUILD_TYPE=Release -DOSP_ENABLE_IWYU=y -DOSP_ENABLE_CLANG_TIDY=y
        scan-build --exclude 3rdparty/newton-dynamics -o scanlogs cmake --build build --parallel --config Release --target osp-magnum

    - name: Prepare Artifact
      run: |
        mv build/3rdparty/newton-dynamics/lib/ build/lib
        
    - uses: actions/upload-artifact@v2
      with: 
        name: release
        path: |
          build/bin
          build/lib